version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mudgame-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: jdsiv5Td6
      MYSQL_DATABASE: mudgame
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
